### ISSUE TITLE
OSC Mouse Issues

### ISSUE THREAD

**Issue by Rabcor** [xylosper/cmplayer#130]
**Default OSC**: If I launch a file and go to fullscreen, the OSC won't fade when the cursor disappears the first time (so after the cursor fades I must move it so it will appear again, and the next time it fades the OSC will fade too)

**Bottom OSC**: Using a bottom-placed OSC  it will not always detect the cursor correctly when it goes down to the bottom of the screen (it's as if the cursor can go lower than the OSC and will not be detected when it is there, resulting in some glitching), another bug is that if you apply/save settings in preferences menu with a bottom-placed OSC, the OSC will be forced to visible and won't hide until fullscreen is exited and then entered again.

**Comment by xylosper** [comment]
These issues should be fixed in LATEST source not 0.8.16. Can you test it?

**Comment by MatthewBregg** [comment]
Thanks for the reply. I just pulled the latest version again, and it seems to be fixed for the OSC, but not the cursor. 
The cursor exhibits the same behavior of getting stuck onscreen until moved. 
Has the version number not changed, since the most recent one from the git still seems to be version 0.8.16? (From the master branch)

**Comment by xylosper** [comment]
Thank you for testing.
The version string is meaning less in git source.
It'll be bumped only if new version is released.
Anyway, I pushed new changes. Please test it again.

**Comment by MatthewBregg** [comment]
Thanks, that seems to fix all the issues.

**Comment by xylosper** [comment]
Thank you for feedback.
